version: '3.8'

services:
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASS}
            MYSQL_DATABASE: ${DB_NAME}
        ports:
            - 3306:3306
            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_HOST: ${DB_HOST}
            PMA_PORT: ${DB_PORT}
            PMA_USER: ${DB_USER}
            PMA_PASSWORD: ${DB_PASS}
        ports:
            - 8082:80
        links:
            - db
        depends_on:
            - db
    
    api:
      build:
        context: ../../
        dockerfile: Dockerfile
      restart: always
      ports:
        - 8080:8080
      volumes:
        - ./src:/app/src
      depends_on:
        - db
      env_file:
        - .env
     